language: dart
dart:
  - "1.22.6"

dart_task:
  - test: --platform vm
  - test: --platform chrome
  # As long as you don't want any other configuration, you can just use the name
  # of a task instead of "name: true".
  - test
  # Warnings are fatal, but we only analyze the lib/ directory.
  - dartanalyzer: --fatal-warnings lib
  - dartfmt
  - test: --exclude-tags no-xvfb
  - test: --tags no-xvfb
  xvfb: false